Repository code-BitLabs/Aquila, pull requests merged in 2023-09, with the labels that each got.

#1 Added Autoloader - Singleton
  .gitignore
  assets/js/bootstrap.min.js
  assets/js/main.js
  assets/style/bootstrap.min.css
  footer.php
  functions.php
  header.php
  inc/classes/class-aquila-theme.php
  inc/helpers/autoloader.php
  inc/traits/trait-singleton.php
  index.php
  template-parts/header/nav.php
Labels: enhancement, help wanted, good first issue

#2 Feature/new feature: theme support & nav Menu
  assets/js/bootstrap.min.js
  functions.php
  inc/classes/class-aquila-theme.php
  inc/classes/class-assets.php
  inc/classes/class-menus.php
  template-parts/header/nav.php
Labels: enhancement, good first issue

#6 BugFix: fix Bootstrap and Other CSS Files Not Loading
  inc/classes/class-assets.php
Labels: bug

#8 Feature/register block pattern
  inc/classes/class-aquila-theme.php
  inc/classes/class-block-patterns.php
Labels: enhancement, help wanted

#9 Feature/block pattern
  assets/src/img/patterns/cover.jpg
  assets/src/js/main.js
  assets/src/sass/0-settings/_variables.scss
  assets/src/sass/2-generic/_gutenberg.scss
  assets/src/sass/main.scss
  front-page.php
  functions.php
  inc/classes/class-block-patterns.php
  template-parts/content-page.php
  template-parts/patterns/cover.php
  template-parts/patterns/two-columns.php
Labels: bug, enhancement, help wanted

#12 Feature/new feature
  archive.php
  assets/src/js/author.js
  assets/src/sass/2-generic/_common-classes.scss
  assets/src/sass/4-layouts/_search-form.scss
  assets/src/sass/4-layouts/header/nav/_navigation.scss
  assets/src/sass/main.scss
  assets/webpack.config.js
  author.php
  date.php
  functions.php
  inc/classes/class-aquila-theme.php
  inc/classes/class-archive-settings.php
  inc/classes/class-assets.php
  inc/classes/class-register-post-types.php
  inc/classes/class-register-taxonomies.php
  inc/helpers/template-tags.php
  template-parts/author/header.php
  template-parts/content.php
  template-parts/header/nav.php
Labels: enhancement, help wanted, good first issue
